name: Coverage

on:
  pull_request:
    paths-ignore:
      - ".vscode"
      - "*.md"
  push:
    branches:
      - main

permissions: {}

jobs:
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    env:
      SCCACHE_GHA_ENABLED: true
      RUSTC_WRAPPER: sccache
    steps:
      - name: Checkout Source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Cache Setup
        uses: mozilla-actions/sccache-action@9e7fa8a12102821edf02ca5dbea1acd0f89a2696 # v0.0.10

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@3235f8901fd37ffed0052b276cec25a362fb82e9 # v2.77.7
        with:
          tool: cargo-llvm-cov

      - name: Generate Coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.out

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.out
          fail_ci_if_error: true
