name: Coverage

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - ".vscode"
      - "*.md"
      - ".github/workflows/docs.yml"
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - ".vscode"
      - "*.md"
      - ".github/workflows/docs.yml"

permissions: {}

jobs:
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    env:
      SCCACHE_GHA_ENABLED: true
      RUSTC_WRAPPER: sccache
    steps:
      - name: Checkout Source
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Cache Setup
        uses: mozilla-actions/sccache-action@9e7fa8a12102821edf02ca5dbea1acd0f89a2696 # v0.0.10

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@fd2f5e3d644b484055ebf4268f474c565f148f25 # v2.81.9
        with:
          tool: cargo-llvm-cov

      - name: Generate Coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.out

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.out
          fail_ci_if_error: true
